version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # when package.lock changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - ~/repo/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

  code_lint:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          keys:
            # when package.lock changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm run lint

  release:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          keys:
            # when package.lock changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - code_lint:
          requires:
            - build
      - release:
          requires:
            - build
            - code_lint
